/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinRouteImport } from './routes/join'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherQuestionsRouteImport } from './routes/teacher/questions'
import { Route as TeacherLoginRouteImport } from './routes/teacher/login'
import { Route as TeacherDashboardRouteImport } from './routes/teacher/dashboard'
import { Route as TeacherAdminRouteImport } from './routes/teacher/admin'
import { Route as PlaySessionIdRouteImport } from './routes/play/$sessionId'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as TeacherSessionSessionIdRouteImport } from './routes/teacher/session/$sessionId'
import { Route as TeacherSessionSessionIdReportRouteImport } from './routes/teacher/session/$sessionId/report'

const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherQuestionsRoute = TeacherQuestionsRouteImport.update({
  id: '/teacher/questions',
  path: '/teacher/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherLoginRoute = TeacherLoginRouteImport.update({
  id: '/teacher/login',
  path: '/teacher/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherDashboardRoute = TeacherDashboardRouteImport.update({
  id: '/teacher/dashboard',
  path: '/teacher/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherAdminRoute = TeacherAdminRouteImport.update({
  id: '/teacher/admin',
  path: '/teacher/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySessionIdRoute = PlaySessionIdRouteImport.update({
  id: '/play/$sessionId',
  path: '/play/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSessionSessionIdRoute = TeacherSessionSessionIdRouteImport.update({
  id: '/teacher/session/$sessionId',
  path: '/teacher/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSessionSessionIdReportRoute =
  TeacherSessionSessionIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => TeacherSessionSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/invite/$token': typeof InviteTokenRoute
  '/play/$sessionId': typeof PlaySessionIdRoute
  '/teacher/admin': typeof TeacherAdminRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/login': typeof TeacherLoginRoute
  '/teacher/questions': typeof TeacherQuestionsRoute
  '/teacher/session/$sessionId': typeof TeacherSessionSessionIdRouteWithChildren
  '/teacher/session/$sessionId/report': typeof TeacherSessionSessionIdReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/invite/$token': typeof InviteTokenRoute
  '/play/$sessionId': typeof PlaySessionIdRoute
  '/teacher/admin': typeof TeacherAdminRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/login': typeof TeacherLoginRoute
  '/teacher/questions': typeof TeacherQuestionsRoute
  '/teacher/session/$sessionId': typeof TeacherSessionSessionIdRouteWithChildren
  '/teacher/session/$sessionId/report': typeof TeacherSessionSessionIdReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/invite/$token': typeof InviteTokenRoute
  '/play/$sessionId': typeof PlaySessionIdRoute
  '/teacher/admin': typeof TeacherAdminRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/login': typeof TeacherLoginRoute
  '/teacher/questions': typeof TeacherQuestionsRoute
  '/teacher/session/$sessionId': typeof TeacherSessionSessionIdRouteWithChildren
  '/teacher/session/$sessionId/report': typeof TeacherSessionSessionIdReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/invite/$token'
    | '/play/$sessionId'
    | '/teacher/admin'
    | '/teacher/dashboard'
    | '/teacher/login'
    | '/teacher/questions'
    | '/teacher/session/$sessionId'
    | '/teacher/session/$sessionId/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/invite/$token'
    | '/play/$sessionId'
    | '/teacher/admin'
    | '/teacher/dashboard'
    | '/teacher/login'
    | '/teacher/questions'
    | '/teacher/session/$sessionId'
    | '/teacher/session/$sessionId/report'
  id:
    | '__root__'
    | '/'
    | '/join'
    | '/invite/$token'
    | '/play/$sessionId'
    | '/teacher/admin'
    | '/teacher/dashboard'
    | '/teacher/login'
    | '/teacher/questions'
    | '/teacher/session/$sessionId'
    | '/teacher/session/$sessionId/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinRoute: typeof JoinRoute
  InviteTokenRoute: typeof InviteTokenRoute
  PlaySessionIdRoute: typeof PlaySessionIdRoute
  TeacherAdminRoute: typeof TeacherAdminRoute
  TeacherDashboardRoute: typeof TeacherDashboardRoute
  TeacherLoginRoute: typeof TeacherLoginRoute
  TeacherQuestionsRoute: typeof TeacherQuestionsRoute
  TeacherSessionSessionIdRoute: typeof TeacherSessionSessionIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/questions': {
      id: '/teacher/questions'
      path: '/teacher/questions'
      fullPath: '/teacher/questions'
      preLoaderRoute: typeof TeacherQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/login': {
      id: '/teacher/login'
      path: '/teacher/login'
      fullPath: '/teacher/login'
      preLoaderRoute: typeof TeacherLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/dashboard': {
      id: '/teacher/dashboard'
      path: '/teacher/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof TeacherDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/admin': {
      id: '/teacher/admin'
      path: '/teacher/admin'
      fullPath: '/teacher/admin'
      preLoaderRoute: typeof TeacherAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$sessionId': {
      id: '/play/$sessionId'
      path: '/play/$sessionId'
      fullPath: '/play/$sessionId'
      preLoaderRoute: typeof PlaySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/session/$sessionId': {
      id: '/teacher/session/$sessionId'
      path: '/teacher/session/$sessionId'
      fullPath: '/teacher/session/$sessionId'
      preLoaderRoute: typeof TeacherSessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/session/$sessionId/report': {
      id: '/teacher/session/$sessionId/report'
      path: '/report'
      fullPath: '/teacher/session/$sessionId/report'
      preLoaderRoute: typeof TeacherSessionSessionIdReportRouteImport
      parentRoute: typeof TeacherSessionSessionIdRoute
    }
  }
}

interface TeacherSessionSessionIdRouteChildren {
  TeacherSessionSessionIdReportRoute: typeof TeacherSessionSessionIdReportRoute
}

const TeacherSessionSessionIdRouteChildren: TeacherSessionSessionIdRouteChildren =
  {
    TeacherSessionSessionIdReportRoute: TeacherSessionSessionIdReportRoute,
  }

const TeacherSessionSessionIdRouteWithChildren =
  TeacherSessionSessionIdRoute._addFileChildren(
    TeacherSessionSessionIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinRoute: JoinRoute,
  InviteTokenRoute: InviteTokenRoute,
  PlaySessionIdRoute: PlaySessionIdRoute,
  TeacherAdminRoute: TeacherAdminRoute,
  TeacherDashboardRoute: TeacherDashboardRoute,
  TeacherLoginRoute: TeacherLoginRoute,
  TeacherQuestionsRoute: TeacherQuestionsRoute,
  TeacherSessionSessionIdRoute: TeacherSessionSessionIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
